service: sls-dynatrace

provider:
  name: aws
  runtime: nodejs12.x
  environment: 
    DT_LAMBDA_OPTIONS: "***"
    DT_TAGS: "***"
    DT_CUSTOM_PROP: "***"

functions:
  hello:
    handler: src/handlers/serviceA/node_modules/@dynatrace/oneagent/index.handler
    environment:
      DT_LAMBDA_HANDLER: "src/handlers/serviceA/index.handler"
    
    events:
      - http:
          path: /
          method: get
