service: sls-antipatterns-shareddatabase-2

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
          - dynamodb:Query
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
      Resource: '*'
  
functions:
  add:
    handler: src/handler.add
    events:
      - http:
          path: add
          method: post

