service: sls-f-appsync-example

plugins:
  - serverless-appsync-plugin
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, "us-east-2"}
  stage: ${opt:stage, "dev"}
  environment:
    TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
          - dynamodb:Query
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
      Resource: "*"
  
custom:
  appSync:
    name: sls-f-appsync-example-api
    authenticationType: API_KEY
    mappingTemplates:
      - dataSource: lambda
        type: Query
        field: listTasks
        request: request.vtl
        response: response.vtl
      - dataSource: lambda
        type: Mutation
        field: createTask
        request: request.vtl
        response: response.vtl
      - dataSource: lambda
        type: Mutation
        field: updateToComplete
        request: request.vtl
        response: response.vtl
      
    mappingTemplatesLocation: src/mapping-templates
    serviceRole: AppSyncServiceRole
    dataSources:
      - type: AWS_LAMBDA
        name: lambda
        description: Notes Lambda function
        config:
          functionName: mainLambda-${opt:stage, "dev"}
          lambdaFunctionArn: { "Fn::GetAtt": ["MainLambdaFunction", "Arn" ] }


functions:
  main:
    name: mainLambda-${opt:stage, "dev"}
    handler: src/handler.main


resources:
  Resources:
      productsTable:
          Type: AWS::DynamoDB::Table
          Properties:
              TableName: ${self:service}-${opt:stage, self:provider.stage}
              AttributeDefinitions:
                  - AttributeName: PK
                    AttributeType: S
                  - AttributeName: SK
                    AttributeType: S
              KeySchema:
                  - AttributeName: PK
                    KeyType: HASH
                  - AttributeName: SK
                    KeyType: RANGE
              BillingMode: PAY_PER_REQUEST