org: serverlessguru
app: serverless-app

service:
  name: serverless-app-count-characters

package:
  exclude:
    - src/**
    - .gitignore
  include:
    - src/handlers/**
    - node_modules/**

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-2"}
  profile: ${opt:profile, "default"}
  apiGateway:
    restApiId: ${output:${self:app}-api.ApiId}
    restApiRootResourceId: ${output:${self:app}-api.ApiResourceId}

custom:
  base: ${self:service}-${self:provider.stage}

functions:
  api:
    name: ${self:custom.base}
    handler: ./handlers/index.handler
    description: Returns the length of a given message
    events:
      - http:
          path: /countCharacters
          method: POST
          cors: true
