org: serverlessguru  # <-- change to your org
app: sls-fargate-eks # <-- change to your app name
service: ${self:app}-iam-user
provider:
  name: aws
  stage: ${opt:stage, "dev"}  # <-- change to your default stage
  region: ${opt:region, "us-east-1"}
custom:
  base: ${self:provider.stage}-${self:provider.region}
resources:
  Resources:
    EKSUser:
      Type: AWS::IAM::User
      Properties:
        Policies:
          - PolicyName: ${self:custom.base}-${self:provider.region}-EKSAdmin
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - eks:*
                  Resource: '*'
          - PolicyName: ${self:custom.base}-${self:provider.region}-EKSCloudFormation
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - cloudformation:*
                  Resource: '*'
          - PolicyName: ${self:custom.base}-${self:provider.region}-EKSTag
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - tag:*
                  Resource: '*'
          - PolicyName: ${self:custom.base}-${self:provider.region}-EKSECR
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - ecr:*
                  Resource: '*'
          - PolicyName: ${self:custom.base}-${self:provider.region}-EKSIAM
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - iam:*
                    # - iam:AddRoleToInstanceProfile
                    # - iam:AttachRolePolicy
                    # - iam:Create*
                    # - iam:Delete*
                    # - iam:DetachRolePolicy
                    # - iam:Get*
                    # - iam:GetRole
                    # - iam:List*
                    # - iam:PassRole
                    # - iam:PutRolePolicy
                    # - iam:RemoveRoleFromInstanceProfile
                  Resource:
                    - '*'
                    # - arn:aws:iam::*:instance-profile/eksctl-*
                    # - arn:aws:iam::*:role/eksctl-*
                    # - arn:aws:iam::*:role/aws-service-role/eks-nodegroup.amazonaws.com/AWSServiceRoleForAmazonEKSNodegroup
                    # - arn:aws:iam::*:oidc-provider/oidc.eks.${self:provider.region}.amazonaws.com/id/*
          - PolicyName: ${self:custom.base}-${self:provider.region}-EKSNetworking
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - elasticloadbalancing:*
                    - acm:*
                    - cognito-idp:*
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - waf-regional:*
                    - waf:*
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - ec2:DeleteInternetGateway
                  Resource:
                    - arn:aws:ec2:*:*:internet-gateway/*
                - Effect: Allow
                  Action:
                    - ec2:*
                    # - ec2:AuthorizeSecurityGroupIngress
                    # - ec2:DeleteSubnet
                    # - ec2:DeleteTags
                    # - ec2:CreateNatGateway
                    # - ec2:CreateVpc
                    # - ec2:AttachInternetGateway
                    # - ec2:DescribeVpcAttribute
                    # - ec2:DeleteRouteTable
                    # - ec2:AssociateRouteTable
                    # - ec2:DescribeInternetGateways
                    # - ec2:CreateRoute
                    # - ec2:CreateInternetGateway
                    # - ec2:RevokeSecurityGroupEgress
                    # - ec2:CreateSecurityGroup
                    # - ec2:ModifyVpcAttribute
                    # - ec2:DeleteInternetGateway
                    # - ec2:DescribeRouteTables
                    # - ec2:ReleaseAddress
                    # - ec2:AuthorizeSecurityGroupEgress
                    # - ec2:DescribeTags
                    # - ec2:CreateTags
                    # - ec2:DeleteRoute
                    # - ec2:CreateRouteTable
                    # - ec2:DetachInternetGateway
                    # - ec2:DescribeNatGateways
                    # - ec2:DisassociateRouteTable
                    # - ec2:AllocateAddress
                    # - ec2:DescribeSecurityGroups
                    # - ec2:RevokeSecurityGroupIngress
                    # - ec2:DeleteSecurityGroup
                    # - ec2:DeleteNatGateway
                    # - ec2:DeleteVpc
                    # - ec2:CreateSubnet
                    # - ec2:DescribeSubnets
                    # - ec2:DescribeAvailabilityZones
                    # - ec2:DescribeImages
                    # - ec2:describeAddresses
                    # - ec2:DescribeVpcs
                  Resource: '*'
    EKSUserCreds:
      Type: AWS::IAM::AccessKey
      Properties:
        UserName:
          Ref: EKSUser
outputs:
  EKSUserAccessKeyId:
    Ref: EKSUserCreds
  EKSUserSecretKey:
    Fn::GetAtt:
      - EKSUserCreds
      - SecretAccessKey
