service: sls-dynamic-config
app: YOUR_APP
org: YOUR_ORG

provider:
  name: aws
  runtime: nodejs12.x

custom:
  resources:
    dev: 
      dbread: 1
      dbwrite: 1
    prod:
      dbread: 5
      dbwrite: 5

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
      productsTable:
          Type: AWS::DynamoDB::Table
          Properties:
              TableName: ${self:service}-${opt:stage, self:provider.stage}
              AttributeDefinitions:
                  - AttributeName: PK
                    AttributeType: S
              KeySchema:
                  - AttributeName: PK
                    KeyType: HASH
              BillingMode: PROVISIONED
              ProvisionedThroughput: 
                ReadCapacityUnits: ${self:custom.resources.${opt:stage, self:provider.stage}.dbread}
                WriteCapacityUnits: ${self:custom.resources.${opt:stage, self:provider.stage}.dbwrite}
